// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfnvtbmpldficuorence.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbnZ0Ym1wbGRmaWN1b3JlbmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Nzk4ODAsImV4cCI6MjA2NDI1NTg4MH0.oxp0Ah1PCaJK4sUG1JBO9dzUSAJ4pHNQ9VGZxA_T9Ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);